export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const SET_GRIDVIEW = 'SET_GRIDVIEW';
export const SET_LISTVIEW = 'SET_LISTVIEW';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const TOGGLE_CART_ITEM_AMOUNT = 'TOGGLE_CART_ITEM_AMOUNT';
export const CLEAR_CART = 'CLEAR_CART';
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS';

export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export const TOGGLE_MEMBER = 'TOGGLE_MEMBER';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';

export const GET_ADDRESSES = 'GET_ADDRESSES';
export const SET_EDIT_ADDRESS = 'SET_EDIT_ADDRESS';
export const HANDLE_SHOW_MODAL = 'HANDLE_SHOW_MODAL';

export const HANDLE_CLOSE_MODAL = 'HANDLE_CLOSE_MODAL';
export const UNSET_EDIT = 'UNSET_EDIT';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_SINGLE_ORDER = 'GET_SINGLE_ORDER';
export const GET_CONFIGS = 'GET_CONFIGS';

export const GET_ME = 'GET_ME';
export const SET_FREE_SHIPPING_FEE = 'SET_FREE_SHIPPING_FEE';

export const SET_CART = 'SET_CART';
export const CHANGE_PAGE = 'CHANGE_PAGE';
